# import Libraries

In [1]:
!pip install psycopg2-binary
!pip install pandas
import psycopg2
from sqlalchemy import create_engine,Table, Column, Integer, String, MetaData,Date
import pandas as pd

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.8.6-cp39-cp39-manylinux1_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 150 kB/s eta 0:00:01     |█████████▏                      | 849 kB 93 kB/s eta 0:00:23     |█████████████████▏              | 1.6 MB 378 kB/s eta 0:00:04     |███████████████████████████████▎| 2.9 MB 150 kB/s eta 0:00:01     |███████████████████████████████▌| 2.9 MB 150 kB/s eta 0:00:01
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.8.6
Collecting pandas
  Downloading pandas-1.2.4-cp39-cp39-manylinux1_x86_64.whl (9.7 MB)
     |████████████████████████████████| 9.7 MB 4.7 MB/s eta 0:00:01     |███████████████████▊            | 6.0 MB 2.5 MB/s eta 0:00:02
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.9/site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.9/site-packages (from pandas) (2021.1)
Collecting numpy>=1.16.5
  Downloading numpy-1.20.3-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.4 MB)
     |████████████████████████████████| 15.4 MB 17.6 MB/s eta 0:00:01   |████▎                           | 2.1 MB 5.3 MB/s eta 0:00:03
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
Installing collected packages: numpy, pandas
Successfully installed numpy-1.20.3 pandas-1.2.4

In [22]:
host="psql_dataenv" # use, 172.26.0.2, "localhost" if you access from outside the localnet decompose env 
database="psql_data_environment"
user="psql_user"
password="psql"
port='5432'
engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{database}')
tablename="client_list"

file_name = 'data.csv'
wdf = pd.read_csv(file_name,index_col='id')



wdf.to_sql(tablename,engine,if_exists='replace',
           dtype={
               "id": Integer,
                "name": String,
                "address": String,
                "company":  String,
                "job_title": String,
                "phone_number": String,
                "created_date": Date})

# Transformation

In [5]:

wdf.sort_values(by=['id'], inplace=True, ascending=False)
wdf.head(10)

,name,address,company,job_title,phone_number,created_date
id,,,,,,
9996,Karen Bruce,"63327 Mack Trail\nCalderonshire, UT 41141",Parks Ltd,Community arts worker,195-962-7475,2020-01-17
9992,Daniel Lopez,"329 Garcia Cove Suite 639\nSouth Patrickhaven,...",Johnson-Le,"Nurse, learning disability",+1-569-093-1213,2017-06-22
9964,Summer Randall,"9576 Rodney Rest Suite 704\nSmithborough, NV 4...","Wong, Jordan and Gibbs",Chief Strategy Officer,907-120-4347x991,2017-09-28
9963,Kevin Mcguire,"4128 Elizabeth Club Suite 179\nSouth Rebecca, ...","Castillo, Taylor and Preston",Sports development officer,(691)840-6902x72697,2015-01-18
9944,Elizabeth Smith,1203 Jeffrey Radial Apt. 852\nWest Jordanmouth...,Fuentes LLC,Software engineer,(727)396-5999x735,2020-09-21
9941,Brett Coffey,"454 Walsh Pine Suite 623\nEast Ashleyberg, ID ...","Potts, Myers and Vance",Actuary,7885552891,2016-11-10
9937,Nancy Martin,"777 John Unions Apt. 675\nPort Staceyfurt, WA ...",Potts Inc,Financial planner,101.666.0218x020,2015-11-02
9918,Roger Mendez,"3297 David Fords Apt. 096\nSouth Leslie, SC 66367","Estes, Ray and Rodriguez",Bookseller,0983528226,2017-02-28
9911,Ryan Young,"9061 Watson Fall\nNew Kimberlymouth, HI 29599","Nguyen, Carr and Moore",Health physicist,(485)343-5968,2017-11-11
9904,James Rosales,"099 Turner Parks Apt. 936\nCrystaltown, TX 43546",Crawford-Tyler,Actor,001-020-903-5725x957,2013-10-09

In [28]:
host="psql_dataenv" # use, 172.26.0.2, "localhost" if you access from outside the localnet decompose env 
database="psql_data_environment"
user="psql_user"
password="psql"
port='5432'
engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{database}')
tablename="client_list"
rdf = pd.read_sql_table(
    tablename,
    con=engine
)

In [29]:
rdf.count()

id              24000
name            24000
address         24000
company         24000
job_title       24000
phone_number    24000
created_date    24000
dtype: int64

In [ ]:
for r in a:  
    print(r)